# database schema
CREATE TABLE IF NOT EXISTS `columns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `order` int(11) NOT NULL DEFAULT '255',
  `parent_id` int(11) NOT NULL DEFAULT '0',
  `is_delete` int(1) NOT NULL DEFAULT '0',
  `comments` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7 ;

CREATE TABLE `contents` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`title` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`content` TEXT CHARACTER SET utf8 NOT NULL ,
`column_id` INT NOT NULL ,
`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`count` INT NOT NULL DEFAULT  '0',
`is_delete` INT NOT NULL DEFAULT  '0'
) ENGINE = MYISAM CHARACTER SET utf8;

CREATE TABLE `report-outer` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`content` TEXT CHARACTER SET utf8 NOT NULL ,
`units` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`leaders` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`sections` TEXT CHARACTER SET utf8 NOT NULL ,
`date` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`place` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`linkman` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`phone` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`note` TEXT CHARACTER SET utf8 NOT NULL ,
`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`status` INT NOT NULL DEFAULT  '0',
`is_delete` INT NOT NULL DEFAULT  '0'
) ENGINE = MYISAM CHARACTER SET utf8;

CREATE TABLE `report-inner` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`content` TEXT CHARACTER SET utf8 NOT NULL ,
`units` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`leaders` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`sections` TEXT CHARACTER SET utf8 NOT NULL ,
`date` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`place` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`linkman` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`phone` VARCHAR( 255 ) CHARACTER SET utf8  NOT NULL ,
`note` TEXT CHARACTER SET utf8 NOT NULL ,
`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`status` INT NOT NULL DEFAULT  '0',
`is_delete` INT NOT NULL DEFAULT  '0'
) ENGINE = MYISAM CHARACTER SET utf8;
